from Modules.PDBe_module import *


#get_summary_info('2asc','false','true')
# get_molecules('1cbs')
# get_publications('1cbs')
# get_experiment('1cbs')
# get_NMR_resource('2k8v')
# get_ligands('1cbs')
# get_modified_residues('4v5j')
# get_mutated_residues('4v5j')
# get_release_status('1cbs')
# get_observed_ranges('1cbs')
# get_observed_ranges_in_PDB_chain('1cbs','A')
# get_secondary_structure('1cbs')
# get_list_of_residues_with_modelling_information('1cbs')
# get_list_of_residues_with_modelling_information_for_a_particular_PDB_chain('1cbs','A')
# get_binding_sites('1cbs')
# get_URLs_of_various_files_associated_with_a_PDB_entry('1cbs')
# get_ratio_of_observed_residues('2k8v','true','true')
